# Number of Conditions

Load file

```{r}
load(file = "C:/Users/DELL/Documents/integration-simulations/index.RData")
library(pracma)
library(ggplot2)
```

See new conditions

```{r}
example = c(seq(0, 0.49, 1/6), seq(0.5, 1, 1/16))
qplot(x = example, y = modulator(example))
```

Now estimate parameters

```{r}
plottingInfoAll = data.frame(Outcome = rep(c("Incorrect & N.S.", 
                                             "Correct & N.S.", 
                                             "Incorrect & p < 0.05",
                                             "Correct & p < 0.05"), times = 4),
                             Count = 0,
                             Conditions = rep(c(2, 3, 6, 12), each = 4))

sampleSize = 60
nTrials = 120
Conditions = c(2, 3, 6, 12)

for (Condition in Conditions){
  if (Condition == 2){
    trialSet = data.frame(Endowment = rep(seq(10, 100, 10), times = 12),
                          Liking = rep(c(0, 1), each = 60))
  } else if (Condition == 3){
    trialSet = data.frame(Endowment = rep(seq(10, 100, 10), times = 12),
                          Liking = rep(c(0, 0.5, 1), each = 40))
  } else if (Condition == 6){
    trialSet = data.frame(Endowment = rep(seq(10, 100, 10), times = 12),
                          Liking = rep(c(seq(0, 0.5, 1/3), 0.5, seq(0.75, 1, 1/8)), each = 20))
  } else {
    trialSet = data.frame(Endowment = rep(seq(10, 100, 10), times = 12),
                          Liking = rep(c(seq(0, 0.49, 1/6), seq(0.5, 1, 1/16)), each = 10))
  }
  df = n1000[sample(200), ]
  df$NLL = 0
  df$NLL_alt = 0
  for (i in 1:nrow(df)){
    row = which(round(freeParameters$theta, 2) == round(df$theta[i], 2) & 
                  round(freeParameters$phi, 2) == round(df$phi[i], 2))
    data = trialSet
    preds = generatePredictions(as.numeric(freeParameters[row,]), data)
    data$Transferred = noise(preds, data$Endowment)
    
    result = tryCatch({fmincon(obj_function,x0 = initial_params,
                       lb = lower_bounds, ub = upper_bounds,
                       df = data)}, error = function(e){data.frame(par = NA)})
    resultAlt = tryCatch({optimizePerCondition(df = data)}, 
                         error = function(e){data.frame(par = NA)})
    if (is.na(resultAlt$par[1]) | is.na(result$par[1])){
      df$NLL[i] = NA; df$NLL_alt[i] = NA; next
    }
    data$Preds = generatePredictions(result$par, data)
    data$PredsAlt = generateAltPerCondition(resultAlt$par, data)
    
    if (sum(data$Preds == data$Transferred)==nrow(data)){
      data$Preds[sample(nrow(data), 1)] =+ 1
    }
    if (sum(data$PredsAlt == data$Transferred)==nrow(data)){
      data$PredsAlt[sample(nrow(data), 1)] =+ 1
    }
    
    df$NLL[i] = -sum(dnorm(data$Transferred/data$Endowment, 
                           mean = data$Preds/data$Endowment, 
                           sd = sd((data$Transferred - data$Preds)/data$Endowment),
                           log = T))
    df$NLL_alt[i] = -sum(dnorm(data$Transferred/data$Endowment, 
                               mean = data$PredsAlt/data$Endowment, 
                           sd = sd((data$Transferred - data$PredsAlt)/data$Endowment), log = T))
  }
  
  df$BIC = 2 * df$NLL + 2 * log(nrow(data))
  df$BIC_alt = 2 * df$NLL_alt + Condition * log(nrow(data))
  test = vector('logical', 100000)
  better = vector('logical', 100000)
  for (i in 1:length(test)){
    subsample = df[sample(1:nrow(df), sampleSize, replace = T), ]
    better[i] = sum(subsample$BIC) < sum(subsample$BIC_alt)
    test[i] = t.test(subsample$BIC, subsample$BIC_alt, paired = T)$p.value < 0.05
  }
  plottingInfoAll$Count[which(plottingInfoAll$Conditions == Condition & 
                              plottingInfoAll$Outcome == "Incorrect & N.S.")] = 
    sum(better==F & test==F)
  plottingInfoAll$Count[which(plottingInfoAll$Conditions == Condition & 
                              plottingInfoAll$Outcome == "Correct & N.S.")] = 
    sum(better==T & test==F)
  plottingInfoAll$Count[which(plottingInfoAll$Conditions == Condition & 
                              plottingInfoAll$Outcome == "Incorrect & p < 0.05")] = 
    sum(better==F & test==T)
  plottingInfoAll$Count[which(plottingInfoAll$Conditions == Condition & 
                              plottingInfoAll$Outcome == "Correct & p < 0.05")] = 
    sum(better==T & test==T)
}
```

And plot

```{r}
plottingInfoAll$Condition = factor(plottingInfoAll$Condition, 
                                levels = c(12, 6, 3, 2))
plottingInfoAll$Outcome = factor(plottingInfoAll$Outcome,
                                 levels = c("Correct & p < 0.05",
                                            "Correct & N.S.", 
                                            "Incorrect & N.S.",
                                            "Incorrect & p < 0.05"))
plottingInfoAll$Proportion = (plottingInfoAll$Count/length(test))

these = which(plottingInfoAll$Outcome == "Correct & p < 0.05")
plottingInfoAll$Position[these] = 1.175

those = which(plottingInfoAll$Outcome == "Correct & N.S.")
plottingInfoAll$Position[those] = 1 - plottingInfoAll$Proportion[these] -
  plottingInfoAll$Proportion[those]/2

plottingInfoAll$Position[those[which(plottingInfoAll$Proportion[these] == 0)]] = 1.175

these = which(plottingInfoAll$Outcome == "Incorrect & p < 0.05")
plottingInfoAll$Position[these] = plottingInfoAll$Proportion[these]/2
those = which(plottingInfoAll$Outcome == "Incorrect & N.S.")
plottingInfoAll$Position[those] = plottingInfoAll$Proportion[these] +
  plottingInfoAll$Proportion[those]/2

if (sum(plottingInfoAll$Proportion == 0) > 0){
  final = plottingInfoAll[-which(plottingInfoAll$Proportion == 0),]
} else {final = plottingInfoAll}

ggplot(data = final, aes(x = Proportion, y = Condition, group = Outcome,
                                   fill = Outcome)) + 
  geom_col() + theme_minimal() + 
  scale_fill_manual(values = c("green", "forestgreen", "firebrick4", "red")) +
  labs(x = "Proportion", y = "Number of Conditions", 
       fill = "Result",
       label = NULL) + 
  geom_label(aes(label = Proportion, x = Position)) + lims(x = c(-0.025, 1.25))
```

Now save workspace for later reference

```{r}
save.image(file = "C:/Users/DELL/Documents/integration-simulations/conditions.RData")
```
